/* [Remove/modify this line not to overwrite this file] */
/* Generated by RPARSE 2021-05-28 15:38 */

/* Reactions:
     @ > beta*PHI > E
     E > sigma*F0*E > I
     E > sigma*(1-F0)*E > A
     A > gammaA*(1-F1)*A > R
     A > gammaA*F1*A > I
     I > gammaI*F2*I > H
     I > gammaI*F2d*I > D
     I > gammaI*(1-F2-F2d)*I > R
     H > gammaH*F3*H > W
     H > gammaH*F3d*H > D
     H > gammaH*(1-F3-F3d)*H > R
     W > gammaW*F4*W > D
     W > gammaW*(1-F4)*W > H
*/

#include <math.h>
#include "propensities.h"
#include "report.h"

enum Species {
  I,
  A,
  E,
  phi,
  H,
  W,
  D,
  R
};

const int NR = 13; /* number of reactions */

/* rate constants */
enum ldataRATE {
  beta,
  PHI
};

enum gdataRATE {
  F0,
  F1,
  F2,
  F2d,
  F3,
  F3d,
  F4,
  sigma,
  gammaI,
  gammaA,
  gammaH,
  gammaW
};

/* forward declaration */
double rFun1(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd);
double rFun2(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd);
double rFun3(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd);
double rFun4(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd);
double rFun5(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd);
double rFun6(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd);
double rFun7(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd);
double rFun8(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd);
double rFun9(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd);
double rFun10(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd);
double rFun11(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd);
double rFun12(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd);
double rFun13(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd);

/* static propensity vector */
static PropensityFun ptr[] = {rFun1,rFun2,rFun3,rFun4,rFun5,rFun6,rFun7,rFun8,rFun9,rFun10,rFun11,rFun12,rFun13};

/* propensity definitions */
double rFun1(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd)
{
  return ldata[beta]*ldata[PHI];
}

double rFun2(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd)
{
  return gdata[sigma]*gdata[F0]*xstate[E];
}

double rFun3(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd)
{
  return gdata[sigma]*(1-gdata[F0])*xstate[E];
}

double rFun4(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd)
{
  return gdata[gammaA]*(1-gdata[F1])*xstate[A];
}

double rFun5(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd)
{
  return gdata[gammaA]*gdata[F1]*xstate[A];
}

double rFun6(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd)
{
  return gdata[gammaI]*gdata[F2]*xstate[I];
}

double rFun7(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd)
{
  return gdata[gammaI]*gdata[F2d]*xstate[I];
}

double rFun8(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd)
{
  return gdata[gammaI]*(1-gdata[F2]-gdata[F2d])*xstate[I];
}

double rFun9(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd)
{
  return gdata[gammaH]*gdata[F3]*xstate[H];
}

double rFun10(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd)
{
  return gdata[gammaH]*gdata[F3d]*xstate[H];
}

double rFun11(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd)
{
  return gdata[gammaH]*(1-gdata[F3]-gdata[F3d])*xstate[H];
}

double rFun12(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd)
{
  return gdata[gammaW]*gdata[F4]*xstate[W];
}

double rFun13(const URDMEstate_t *xstate,double time,double vol,
             const double *ldata,const double *gdata,int sd)
{
  return gdata[gammaW]*(1-gdata[F4])*xstate[W];
}

/* URDME solver interface */
PropensityFun *ALLOC_propensities(size_t Mreactions)
{
  if (Mreactions > NR) PERROR("Wrong number of reactions.");
  return ptr;
}

void FREE_propensities(PropensityFun *ptr)
{ /* do nothing since a static array was used */ }

